/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modulesapp;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Yo
 */
public class ModuleGUI extends javax.swing.JFrame {
    Module m;
    ArrayList <Module> logs;
    /**
     * Creates new form ModuleGUI
     */
    public ModuleGUI() {
        initComponents();
        moduleNameLB.setVisible(false);
        lecturerLB.setVisible(false);
        dayAndTimeLB.setVisible(false);
        firstLectureLB.setVisible(false);
        secondLectureLB.setVisible(false);
        moduleNameTA.setVisible(false);
        lecturerTA.setVisible(false);
        dayAndTimeTA.setVisible(false);
        firstLectureTA.setVisible(false);
        secondLectureTA.setVisible(false);
        logs = new ArrayList();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BusinessBT = new javax.swing.JButton();
        TechnicalBT = new javax.swing.JButton();
        moduleNameLB = new javax.swing.JLabel();
        moduleNameTA = new javax.swing.JTextField();
        lecturerLB = new javax.swing.JLabel();
        lecturerTA = new javax.swing.JTextField();
        dayAndTimeLB = new javax.swing.JLabel();
        dayAndTimeTA = new javax.swing.JTextField();
        firstLectureLB = new javax.swing.JLabel();
        firstLectureTA = new javax.swing.JTextField();
        secondLectureLB = new javax.swing.JLabel();
        secondLectureTA = new javax.swing.JTextField();
        addBT = new javax.swing.JButton();
        displayBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BusinessBT.setText("Business Modules");
        BusinessBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusinessBTActionPerformed(evt);
            }
        });

        TechnicalBT.setText("Technical Modules");
        TechnicalBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TechnicalBTActionPerformed(evt);
            }
        });

        moduleNameLB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        moduleNameLB.setText("Module name:");

        moduleNameTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduleNameTAActionPerformed(evt);
            }
        });

        lecturerLB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lecturerLB.setText("Lecturer:");

        lecturerTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerTAActionPerformed(evt);
            }
        });

        dayAndTimeLB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dayAndTimeLB.setText("Lecture Day/Time:");

        dayAndTimeTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayAndTimeTAActionPerformed(evt);
            }
        });

        firstLectureLB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        firstLectureLB.setText("First Lecture:");

        firstLectureTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstLectureTAActionPerformed(evt);
            }
        });

        secondLectureLB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        secondLectureLB.setText("Second Lecture:");

        secondLectureTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondLectureTAActionPerformed(evt);
            }
        });

        addBT.setText("Add");
        addBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTActionPerformed(evt);
            }
        });

        displayBT.setText("Display");
        displayBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dayAndTimeLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(dayAndTimeTA, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstLectureLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(secondLectureLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(481, 481, 481))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(moduleNameLB, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lecturerLB, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(163, 163, 163)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(firstLectureTA, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(secondLectureTA, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moduleNameTA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lecturerTA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBT)
                        .addGap(18, 18, 18)
                        .addComponent(displayBT))
                    .addComponent(TechnicalBT, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BusinessBT, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(242, 242, 242))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moduleNameTA)
                    .addComponent(moduleNameLB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lecturerLB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dayAndTimeLB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstLectureLB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secondLectureLB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lecturerTA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dayAndTimeTA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(firstLectureTA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(secondLectureTA)
                        .addGap(24, 24, 24)
                        .addComponent(BusinessBT, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TechnicalBT, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBT)
                            .addComponent(displayBT))
                        .addGap(133, 133, 133))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BusinessBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusinessBTActionPerformed
        // TODO add your handling code here:
        moduleNameLB.setVisible(true);
        lecturerLB.setVisible(true);
        dayAndTimeLB.setVisible(true);
        firstLectureLB.setVisible(true);
        secondLectureLB.setVisible(true);
        moduleNameTA.setVisible(true);
        lecturerTA.setVisible(true);
        dayAndTimeTA.setVisible(true);
        firstLectureTA.setVisible(true);
        secondLectureTA.setVisible(true);
        
        m = new BusinessModules();
    }//GEN-LAST:event_BusinessBTActionPerformed

    private void TechnicalBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TechnicalBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TechnicalBTActionPerformed

    private void moduleNameTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleNameTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moduleNameTAActionPerformed

    private void lecturerTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturerTAActionPerformed

    private void dayAndTimeTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayAndTimeTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayAndTimeTAActionPerformed

    private void firstLectureTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstLectureTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstLectureTAActionPerformed

    private void secondLectureTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondLectureTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondLectureTAActionPerformed

    private void addBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTActionPerformed
        // TODO add your handling code here:
        if(m instanceof BusinessModules){
            String name = moduleNameTA.getText();
            String lecturer = lecturerTA.getText();
            String dayAndTime = dayAndTimeTA.getText();
            String fLecture = firstLectureTA.getText();
            String sLecture = secondLectureTA.getText();
            
            m.setModuleName(name);
            m.setLecturer(lecturer);
            m.setLectureDayAndTime(dayAndTime);
            ((BusinessModules)(m)).setfTutorialDayAndTime(fLecture);
            ((BusinessModules)(m)).setsTutorialDayAndTime(sLecture);
            
            logs.add(m);
        }
    }//GEN-LAST:event_addBTActionPerformed

    private void displayBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTActionPerformed
        // TODO add your handling code here:
        if(m instanceof BusinessModules){
            for(int i=0;i<logs.size();i++){
                JOptionPane.showMessageDialog(null, logs.get(i).printDetails());
            }
        }
    }//GEN-LAST:event_displayBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuleGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BusinessBT;
    private javax.swing.JButton TechnicalBT;
    private javax.swing.JButton addBT;
    private javax.swing.JLabel dayAndTimeLB;
    private javax.swing.JTextField dayAndTimeTA;
    private javax.swing.JButton displayBT;
    private javax.swing.JLabel firstLectureLB;
    private javax.swing.JTextField firstLectureTA;
    private javax.swing.JLabel lecturerLB;
    private javax.swing.JTextField lecturerTA;
    private javax.swing.JLabel moduleNameLB;
    private javax.swing.JTextField moduleNameTA;
    private javax.swing.JLabel secondLectureLB;
    private javax.swing.JTextField secondLectureTA;
    // End of variables declaration//GEN-END:variables
}
